# Generated by Django 4.2.23 on 2025-07-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='frequency',
            field=models.CharField(choices=[('one-off', 'One-Off'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='one-off', max_length=20),
        ),
        migrations.AddField(
            model_name='club',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
