# Generated by Django 4.2.23 on 2025-08-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_club_created_at_club_teacher_club_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='club_or_event',
            field=models.CharField(choices=[('club', 'Club'), ('event', 'Event')], default='club', max_length=6),
        ),
    ]
