# Generated by Django 4.2.23 on 2025-08-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0002_alter_child_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='child',
            name='surname',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
